import { useMemo, useState, type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, ArrowUpRight, Check, Edit3, Mail, Search, Users } from 'lucide-react';
import { useOrders, useStore } from '../../contexts/CommerceContext';
import { useUI } from '../../contexts/UIContext';
import { formatDate, money } from '../../lib/storage';
import { Badge, Button, Field, Modal } from '../../components/ui';
import { AdminPageHeading } from './Dashboard';
import type { Product, StoreSettings } from '../../types';

export function AdminCustomers() {
  const { orders } = useOrders();
  const [search, setSearch] = useState('');
  const [selected, setSelected] = useState<string | null>(null);
  const customers = useMemo(() => Array.from(new Map([...orders].reverse().map((order) => [order.customer.email, order.customer])).values()).map((customer) => {
    const customerOrders = orders.filter((order) => order.customer.email === customer.email);
    return { ...customer, orders: customerOrders, total: customerOrders.filter((order) => order.status !== 'Cancelled').reduce((sum, order) => sum + order.total, 0) };
  }), [orders]);
  const filtered = customers.filter((customer) => `${customer.name} ${customer.email} ${customer.city}`.toLowerCase().includes(search.toLowerCase()));
  const customer = customers.find((entry) => entry.email === selected);
  return <><AdminPageHeading eyebrow="IN GOOD COMPANY" title="Your community" description="The people making Aurel a part of their story."><span className="admin-heading-count"><Users size={16} />{customers.length} customers</span></AdminPageHeading><section className="admin-panel"><div className="admin-table-toolbar"><label className="admin-table-search"><Search size={16} strokeWidth={1.3} /><input aria-label="Search customers" placeholder="Search name, email, or city..." value={search} onChange={(event) => setSearch(event.target.value)} /></label></div><div className="table-scroll"><table className="admin-table"><thead><tr><th>CUSTOMER</th><th>CONTACT</th><th>LOCATION</th><th>ORDERS</th><th>TOTAL SPENT</th><th /></tr></thead><tbody>{filtered.map((person) => <tr key={person.email}><td><div className="table-customer"><span>{person.name.split(' ').map((part) => part[0]).slice(0, 2).join('')}</span><strong>{person.name}</strong></div></td><td>{person.email}<small>{person.phone}</small></td><td>{person.city}<small>{person.state}</small></td><td>{person.orders.length}</td><td>{money(person.total)}</td><td><button className="admin-view-button" onClick={() => setSelected(person.email)}>VIEW <ArrowUpRight size={13} /></button></td></tr>)}</tbody></table></div>{!filtered.length && <p className="table-empty">No customers match this search.</p>}<div className="table-footer"><span>{filtered.length} of {customers.length} customers</span><span>Sample customer data</span></div></section><Modal open={Boolean(customer)} onClose={() => setSelected(null)} title="A member of our community">{customer && <div className="customer-modal"><div className="customer-avatar-name"><span>{customer.name[0]}</span><div><h3>{customer.name}</h3><p>{customer.city}, {customer.state}</p></div></div><dl className="specification-list"><div><dt>Email</dt><dd>{customer.email}</dd></div><div><dt>Phone</dt><dd>{customer.phone}</dd></div><div><dt>Address</dt><dd>{customer.address}, {customer.pincode}</dd></div><div><dt>Total spent</dt><dd>{money(customer.total)}</dd></div></dl><p className="eyebrow">THEIR AUREL CHAPTERS</p>{customer.orders.map((order) => <Link key={order.id} to={`/admin/orders/${order.id}`} onClick={() => setSelected(null)}><div><strong>{order.id}</strong><span>{formatDate(order.date)}</span></div><Badge status={order.status} /><ArrowRight size={15} /></Link>)}</div>}</Modal></>;
}

function EditProduct({ product, close }: { product: Product; close: () => void }) {
  const [draft, setDraft] = useState(product);
  const { updateProduct } = useStore();
  const { toast } = useUI();
  const submit = (event: FormEvent) => { event.preventDefault(); updateProduct(draft); toast('Your piece has been updated across the storefront.'); close(); };
  return <form className="product-edit-form" onSubmit={submit}><img src={product.image} alt={product.name} /><div className="form-grid"><Field className="form-full" label="Product name" required value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} /><Field label="Price (INR)" type="number" required min="1" max="10000000" step="1" value={draft.price} onChange={(event) => setDraft({ ...draft, price: Number(event.target.value) })} /><label className="field"><span>AVAILABILITY</span><select value={draft.available ? 'available' : 'unavailable'} onChange={(event) => setDraft({ ...draft, available: event.target.value === 'available' })}><option value="available">Available</option><option value="unavailable">Out of stock</option></select></label><label className="field form-full"><span>DESCRIPTION</span><textarea required rows={4} value={draft.description} onChange={(event) => setDraft({ ...draft, description: event.target.value })} /></label></div><div className="product-edit-actions"><Button type="button" variant="outline" onClick={close}>CANCEL</Button><Button type="submit">SAVE CHANGES <Check size={14} /></Button></div></form>;
}

export function AdminProducts() {
  const { catalog } = useStore();
  const [search, setSearch] = useState('');
  const [category, setCategory] = useState('All categories');
  const [editing, setEditing] = useState<Product | null>(null);
  const filtered = catalog.filter((product) => `${product.name} ${product.material}`.toLowerCase().includes(search.toLowerCase()) && (category === 'All categories' || product.category === category));
  return <><AdminPageHeading eyebrow="THE CONSIDERED COLLECTION" title="Your pieces" description="Beautifully crafted. Thoughtfully managed."><Link to="/shop" className="admin-text-link">VIEW THE STOREFRONT <ArrowUpRight size={14} /></Link></AdminPageHeading><section className="admin-panel"><div className="admin-table-toolbar"><label className="admin-table-search"><Search size={16} strokeWidth={1.3} /><input placeholder="Find a piece..." aria-label="Search products" value={search} onChange={(event) => setSearch(event.target.value)} /></label><select aria-label="Product category" value={category} onChange={(event) => setCategory(event.target.value)}>{['All categories', 'Rings', 'Necklaces', 'Earrings', 'Bracelets', 'Bangles'].map((value) => <option key={value}>{value}</option>)}</select></div><div className="table-scroll"><table className="admin-table"><thead><tr><th>PIECE</th><th>CATEGORY</th><th>COLLECTION</th><th>PRICE</th><th>AVAILABILITY</th><th>ACTIONS</th></tr></thead><tbody>{filtered.map((product) => <tr key={product.id}><td><div className="table-product"><img src={product.image} alt={product.name} /><span>{product.name}<small>{product.material}</small></span></div></td><td>{product.category}</td><td>{product.collection}</td><td>{money(product.price)}</td><td><Badge status={product.available ? 'Active' : 'Pending'}>{product.available ? 'Available' : 'Out of stock'}</Badge></td><td><div className="card-table-actions"><button aria-label={`Edit ${product.name}`} onClick={() => setEditing(product)}><Edit3 size={15} /></button><Link to={`/product/${product.id}`} aria-label={`View ${product.name}`}><ArrowUpRight size={16} /></Link></div></td></tr>)}</tbody></table></div>{!filtered.length && <p className="table-empty">No pieces match this search.</p>}<div className="table-footer"><span>{filtered.length} of {catalog.length} pieces</span><span>Changes are saved locally and reflected in the storefront</span></div></section><Modal open={Boolean(editing)} onClose={() => setEditing(null)} title="Consider the details">{editing && <EditProduct key={editing.id} product={editing} close={() => setEditing(null)} />}</Modal></>;
}

export function AdminSettings() {
  const { settings, saveSettings } = useStore();
  const { toast } = useUI();
  const [draft, setDraft] = useState<StoreSettings>(settings);
  const save = (event: FormEvent) => { event.preventDefault(); saveSettings(draft); toast('Your atelier settings have been saved.'); };
  return <><AdminPageHeading eyebrow="THE LITTLE DETAILS MATTER" title="Atelier settings" description="Make this thoughtful space your own." /><form onSubmit={save} className="settings-form"><section className="admin-panel"><div className="admin-panel-heading"><div><h2>Your store</h2><p>Contact details shown in the footer and digital purchase cards.</p></div></div><div className="settings-fields form-grid"><Field className="form-full" label="Store name" required value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} /><Field label="Contact email" type="email" required value={draft.email} onChange={(event) => setDraft({ ...draft, email: event.target.value })} /><Field label="Contact phone" type="tel" required value={draft.phone} onChange={(event) => setDraft({ ...draft, phone: event.target.value })} /><Field className="form-full" label="Store address" required value={draft.address} onChange={(event) => setDraft({ ...draft, address: event.target.value })} /></div></section><section className="admin-panel"><div className="admin-panel-heading"><div><h2>A little heads-up</h2><p>Keep an eye on the things that need your attention.</p></div><Mail size={19} strokeWidth={1.2} /></div><label className="settings-toggle"><div><strong>Order notification indicator</strong><p>Show an unread indicator when orders are awaiting confirmation.</p></div><input type="checkbox" checked={draft.orderNotifications} onChange={(event) => setDraft({ ...draft, orderNotifications: event.target.checked })} /></label></section><section className="settings-security"><p className="eyebrow">ABOUT THIS WORKSPACE</p><p>This is a frontend-only demo. Admin credentials and OTP checks are simulated in isolated service adapters. Orders, catalog edits, settings, and cards persist in localStorage. Do not use real customer information.</p><p>Admin: admin@jewellerydemo.com / admin123<br />Card verification: 123456</p></section><Button type="submit">SAVE SETTINGS <Check size={14} /></Button></form></>;
}